### ISSUE TITLE
Create about/documentation/credits section

### ISSUE THREAD

**Issue by hrecht** [home-fire-risk/smoke_alarm_map#15]
About section should contain documentation for users including instructions for users, a quick description of what goes into the models, data source info, credit links where needed, anything else the RC would find helpful or requires, etc. This could be a section above or below the map or a box that appears on clicking an info button (depending on length) or a separate page. 
It would be great if the text could be worked on via Google doc for easy collaboration and RC input.

**Comment by brooksandrew** [comment]
@hrecht I started a google doc to start drafting this language 

https://docs.google.com/document/d/1UgcWG3Z1vCd81cyk9MTNBENZK2IJZ1A1DyMVw8xQa6s/edit

**Comment by d3netxer** [comment]
From a design perspective, what about if there no about sections above the map and no data sections below the map?

The Map can again take up the whole view. The top menu bar gets retained and when the user clicks on the 'About' or 'Table' link a pop-up appears with the respective information.

**Comment by brooksandrew** [comment]
Thanks @d3netxer for the design idea.  I'm no designer, but I think that could work nicely, as long as it's clear to the user that there is a data view available.  @hrecht what do you think?  I know you had mentioned some thoughts about the intro/landing page at the Dive.
@d3netxer - if you're interested in testing out that design, feel free to contribute to the repo, perhaps in a branch to start, if it's a re-design vs feature enhancement.

**Comment by hrecht** [comment]
Just saw this, sorry for the delay @d3netxer @brooksandrew! I made a new branch to try out that popup style. I think it works nicely. https://github.com/home-fire-risk/smoke_alarm_map/tree/style-updates Open to feedback/PRs.
Also added the latest text from RC.
