### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by dalekunce** [home-fire-risk/smoke_alarm_map#28]
Add the Red Cross logo. Ours always goes on top :)

http://www.redcross.org/about-us/media-resources/logo/brand-standards

<img width="277" alt="screen shot 2016-06-19 at 6 55 25 pm" src="https://cloud.githubusercontent.com/assets/1913857/16180294/760aafb2-364f-11e6-9e01-8b58c0361366.png">

<img width="442" alt="screen shot 2016-06-19 at 6 56 52 pm" src="https://cloud.githubusercontent.com/assets/1913857/16180312/b18395b8-364f-11e6-9fd6-a60c93686ae8.png">

- [ ] about page
- [ ] page header

**Comment by brooksandrew** [comment]
@dalekunce do you have a particular recommended RC logo image or style for apps like these?  If it's not a big deal, we can also just grab one from the RC site or Google.

**Comment by dalekunce** [comment]
Please use as described in the brand standards

**Comment by brooksandrew** [comment]
@dalekunce ah oops overlooked the link.  thanks

**Comment by hrecht** [comment]
Home fire risk team decided no logo (via email)
