### ISSUE TITLE
make census -> ARC geographies crosswalk

### ISSUE THREAD

**Issue by hrecht** [home-fire-risk/smoke_alarm_map#5]
Create a crosswalk CSV between Census and ARC geographies, from ARC boundaries: 
http://maps.redcross.org/website/Services/Data/2015_Chapter_Alignment_Master_No_Contacts.xlsx
(saved on page http://maps.redcross.org/website/Services/ARC_Services.html)
From tab COUNTY_CHAP_NO_CONTACTS: 
save columns:
* County Fips
* County Name
* Chapter Code
* Chapter Name
* Region Code
* Region Name

Save data as a CSV for later use in map

**Comment by brooksandrew** [comment]
merged onto risk_tract.csv from aggregate_risk repo here: home-fire-risk/smoke_alarm_models@b0354032b5356c335bed8bda565da7542b08d189
